language: python
python:
- 3.6
#- 3.5
#- 3.4
#- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: qikk
  password:
    secure: VPvJpOCuLm8MZKLRNHsTPRWB9Rd63+9sSsFuEAmnfMJeEseVSmqdZM2kpCu7TkJPCx1+igqvv1esqlWER/BNnE4EUxD3HWh1D3KCax/pQzv0+vqvcmONB2Ytueq/TLfWPSJfQl7xM8kw1X8O3SJ9iZYJlA6VtO+2UIPyY42GqJeXXnBkQr1PVjfkwQEFbP8I3a58rWK6fYBsPFkLYxCpyaM7f2wnlrnCQSw3vzmNafY5dKEIyZBKj2zqOjpD8evtbG6Z9XFepTKGlJfDN75Znybo5huOPj9aVD9s6lKG7bFIMWrCN1bXZMNgn+2rYFiPLerKMc6rFV89eXZ3ZoORbCveiYLa13kj/8xzQCwidBr+liJk2RKnDK38G50iJXFxWUvMkOIgzfcqDap2zhINpP1qKy6h1uBvjM58Ienb5V4PmmycauXUpe04wzVJXPA8Iw/2Lbt3Xun7mHG0tK0HxgWUw6JuFfTZA526iukgs/JnRjdbnMCfGzHrTw+FzQ/K4evzRT62oCCfdLnIk4oGSSiawpkmfqJ/qAynfA9zLlQYkgRazNucBviBDZibczmprtokILGy4HDkKiNDFWg6fPp+yCW7Sux4lj/byTOeDkG7FvhKGiBN9OlvLWbt/FQxBIEPcJ/whQbK1KzggstaybA4AU9sovGYtk/kco0Kk68=
  on:
    tags: true
    repo: iamkkqi/mcc
    python: 3.6
before_install:
    sudo add-apt-repository ppa:mc3man/trusty-media
    sudo apt-get update
    sudo apt-get install ffmpeg
